services:
  runner:
    image: wpkpda/github-actions-runner:v1.0.0
    pull_policy: always
    environment:
      - URL=
      - TOKEN=
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
